### ISSUE TITLE
When I was training, there was an error message that the function of "load_model" was missing, could you give me the missing code?

### ISSUE THREAD

**Issue by warren-126** [robert80203/GSVNet#1]
Traceback (most recent call last):
  File "main.py", line 61, in <module>
Traceback (most recent call last):
      File "main.py", line 61, in <module>
trainer = GSVNet_Trainer(args)
  File "/data/yyf/video_network/GSVNet/trainer/gsvnet_trainer.py", line 32, in __init__
    super().__init__(args, args.segnet + "_" + args.checkname)
  File "/data/yyf/video_network/GSVNet/trainer/base.py", line 198, in __init__
    trainer = GSVNet_Trainer(args)
  File "/data/yyf/video_network/GSVNet/trainer/gsvnet_trainer.py", line 32, in __init__
    super().__init__(args, args.segnet + "_" + args.checkname)
  File "/data/yyf/video_network/GSVNet/trainer/base.py", line 198, in __init__
    self.network = self.init_network(args, self.num_classes)
  File "/data/yyf/video_network/GSVNet/trainer/gsvnet_trainer.py", line 113, in init_network
    self.network = self.init_network(args, self.num_classes)
  File "/data/yyf/video_network/GSVNet/trainer/gsvnet_trainer.py", line 113, in init_network
    self.segnet = self.init_segnet(args, num_classes)
  File "/data/yyf/video_network/GSVNet/trainer/gsvnet_trainer.py", line 83, in init_segnet
    self.segnet = self.init_segnet(args, num_classes)
  File "/data/yyf/video_network/GSVNet/trainer/gsvnet_trainer.py", line 83, in init_segnet
    from model.bisenet.bisenet_resnet18 import BiSeNet as BiSeNet_Resnet
  File "/data/yyf/video_network/GSVNet/model/bisenet/bisenet_resnet18.py", line 8, in <module>
    from model.bisenet.bisenet_resnet18 import BiSeNet as BiSeNet_Resnet
  File "/data/yyf/video_network/GSVNet/model/bisenet/bisenet_resnet18.py", line 8, in <module>
    from model.bisenet.resnet import resnet18
  File "/data/yyf/video_network/GSVNet/model/bisenet/resnet.py", line 4, in <module>
    from model.bisenet.resnet import resnet18
  File "/data/yyf/video_network/GSVNet/model/bisenet/resnet.py", line 4, in <module>
    from util.general import load_model
    ImportErrorfrom util.general import load_model: 
**cannot import name 'load_model' from 'util.general'** (/data/yyf/video_network/GSVNet/**util/general.py**)
ImportError: cannot import name 'load_model' from 'util.general' (/data/yyf/video_network/GSVNet/util/general.py)

**Comment by robert80203** [comment]
Hello,

I have updated general.py with load_model().
It should work now. Thanks.
